modLoader="javafml"
loaderVersion = "[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = false
versionRange = "[1.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "gtmthings"
mandatory = false
versionRange = "[1.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "extendedae"
mandatory = false
versionRange = "[1.1,)"
ordering = "AFTER"
side = "BOTH"